---
title: "rflow example 2"
author: "Vaclav Hausenblas"
date: "26/12/2018"
output: html_document
params:
  rflow: "./inst/db2"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dependencies}
library(magrittr)
library(DBI)
library(data.table)
library(Rflow)

# source("./tools/tools.R", encoding = "UTF-8")
# source("./tools/r6.R",    encoding = "UTF-8")
```


## R environments definition and setup

TODO: obecne zajistit existenci/pripojeni/inicializaci (ze souboru). V pripade DB pripojeni zajistit jejich connection. 

```{r init connections and environments}
# R environment
.GlobalEnv[["RE1"]] <- new.env(parent = .GlobalEnv)

# establish SQLite connection / environment
DB1 <- list(con = DBI::dbConnect(RSQLite::SQLite(), ":memory:"))
```

# Main

```{r DAG}
RF <- new_rflow(path = params$rflow)
# Rflow::clean_cache(RF)
# Rflow::clean_persistence(RF)
```



```{r load obj definitions from files}
# r_node$debug("initialize")
load_nodes(RF)
# Rflow:::check_rflow_dag(RF)
```

```{r}
plot(RF)
# View(nodes(RF))
```

```{r make}
make(RF)
```


## Tests

```{r test DB tables}
DBI::dbReadTable(DB1$con, "tab1")
DBI::dbReadTable(DB1$con, "tab2")
DBI::dbReadTable(DB1$con, "tab3")
```



## MAIN LOOP

update from config files -> connect -> make


# Finish

```{r disconnect}
DBI::dbDisconnect(DB1$con)
```

<!-- ```{r, save DAG} -->
<!-- if (!dir.exists("./.rflow")) dir.create(path = "./.rflow") -->
<!-- save(list = ls(DAG, all.names = TRUE), envir = DAG, file = "./.rflow/DAG.RData") -->
<!-- ``` -->

