---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

```

# Rflow

Rflow is an R package providing R users with a general-purpose workflow framework. Rflow allows you to describe your data declaratively as objects with dependencies and does the heavy lifting for you. It is suitable for various purposes: from managing several simple automation scripts to building powerfull ETL pipelines.


Rflow makes your data pipelines better organized and managable (worflow can be visualized, objects may have documentation and tags).

It saves your time as your objects are rebuild only when its needed (also objects are persistent over sessions).


**Development of `Rflow` package is still in its beta version phase (some breaking changes may happen).**


## Usecases

1. We have a complex suite of scripts that prepare data from various sources for analysis or publication. We need to update our output whenever some of the inputs changes or when some of the scripts are changed.

2. We want to get data from a database, transform them in R and then upload them back to the database (or other place).

3. We have complex long-running computations that need to be run only when parameters changes.


## Getting started


### Prerequisites

* `R` (>= 3.5.3 tested)
* `devtools` package

```r
install.packages("devtools")
```


### Installation

Rflow is hosted on GitHub. The easies way to install it is by using `devtools` package:

```r
devtools::install_github("vh-d/Rflow")
```



## How it works

**Rflow** is a DAG connecting nodes through dependency relations. There are three building blocks of rflows:

* **nodes** (aka targets) represent your data objects such as R values, db tables, spreadsheets, files, etc...
* **environments** serves as containters for nodes. For example a database is a container for database tables, R environemnt is a container for R objects, etc...
* **jobs** represents dependency connection between nodes. It carries the recipe how to build a target object.



## Examples

```r
.RFLOW <- Rflow::new_rflow()
```

We can define the target nodes using TOML files or directly in R as a list:

```r
objs <- 
  list(
    
    "DB.mytable" = list(
      type = "db_node",
      desc = "A db table with data that serves as source for further computation"
    ),
    
    "mytable_summary" = list(
      type = "r_node", # unnecessary for R objects
      desc = "Summary statistics of DB.mytable",
      r_expr = expression_r({
        .RFLOW[["DB.mytable"]] %>% 
          RETL::etl_read() %>% 
          summary()
      })
    ),
    
    "main_product" = list(
      desc = "Main output",
      r_expr = expression_r({
        .RFLOW[["DB.mytable"]] %>% some_fancy_computation()
      })
    ),
    
    "DB.output" = list(
      desc = "Outcome is loaded back to the DB",
      r_expr = expression_r({
        .RFLOW[["main_product"]] %>%
          RETL::etl_write(to = self)
      })
    )
  ) 
```

Now we can add these definitions into an existing workflow:

```r
objs %>% 
  Rflow::process_obj_defs() %>% 
  Rflow::add_nodes(rflow = .RFLOW)
```

and visualize

```r
Rflow::visRflow(.RFLOW)
```

or build targets

```r
make(.RFLOW)
```


## TODO:

**Features**

* Implement jobs as S3 classes
  * add possibility to keep R/SQL code in standalone R scripts
  * add more types of jobs (bash, Python, Julia, ...)
* Add more nuanced `verbose` options
* Add proper logging for rflow object
* Improve handling of obsolete nodes
  * removing objects from DAG
  * removing cache
  * removing node config files
  * deleting represented objects
* Allow deleting properties / setting some to NULL
  * currently, if a property is deleted update() method ignores it
* Add query function over multiple nodes to set or get fields
* Finish documentation
  * Add quick start guide
* Add new node types:
  * test node
* Advance db_node class
  * other types of objects (Views, indexes, ...)
* Build a Shiny app for Rflow management 
* Implement parallel evaluation (futures?)
* Make all public properties active (mutation would trigger persistence storage)
* Migrate from R6 to S3 classes?
* Experiment with proper ORM instead of serialization of selected properties 
* Add an environment class
* Make methods initializing and updating properties more generic.
* Improve test coverage
