---
title: "rflow example 2"
author: "Vaclav Hausenblas"
date: "26/12/2018"
output: html_document
params:
  rflow: "./inst/db2_list"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dependencies}
library(magrittr)
library(DBI)
library(data.table)
library(Rflow)

# source("./tools/tools.R", encoding = "UTF-8")
# source("./tools/r6.R",    encoding = "UTF-8")
```


## R environments definition and setup

TODO: obecne zajistit existenci/pripojeni/inicializaci (ze souboru). V pripade DB pripojeni zajistit jejich connection. 

```{r init connections and environments}
# R environment
.GlobalEnv[["RE1"]] <- new.env(parent = .GlobalEnv)

# establish SQLite connection / environment
DB1 <- list(con = DBI::dbConnect(RSQLite::SQLite(), ":memory:"))
```

# Main

```{r DAG}
RF <- new_rflow(path = params$rflow)
Rflow::clean_cache(RF)
Rflow::clean_persistence(RF)
```



```{r load obj definitions from files}
obj_defs <- 
  list(
    "RE1.tab1" =
      list(
        tags = c("table"),
        type = "r_node",
        r_expr =
          expression({
            N = 10; 
            data.table(id = 1:N, value = rnorm(N))
          }),
        trigger_condition = 
          expression({
            as.numeric(Sys.time() - last_evaluated, units = "secs") > 10
          })
      ), 
    
    "DB1.tab1" = 
      list(
        tags    = c("db", "table"),
        type    = "db_node",
        depends = "RE1.tab1",
        con_code= "DB1$con",
        r_expr  = 
          expression({
            DBI::dbWriteTable(
              conn = DB1$con, 
              name = 'tab1', 
              value = RE1$tab1, 
              overwrite = TRUE
            )
          })
      ), 
    
    # unnamed object
    list(
      env  = "RE1",
      name = "tab2",
      tags = c("table", "R"),
      type = "r_node",
      r_code = "{N = 20;data.table(id = 1:N, value = rnorm(N))}"
    )
  )

# debug(process_obj_defs)
obj_defs <- process_obj_defs(obj_defs)
str(obj_defs)

```

```{r}
add_nodes(
  objs        = obj_defs,
  rflow       = RF,
  conflict    = "update",
  cache       = RF$.cache$path,
  verbose     = TRUE
)

```


```{r}
plot(RF)
# View(nodes(RF))
```

```{r make}
make(RF, tags = "db")
```


## Tests

```{r test DB tables}
DBI::dbReadTable(DB1$con, "tab1")
DBI::dbReadTable(DB1$con, "tab2")
DBI::dbReadTable(DB1$con, "tab3")
```



## MAIN LOOP

update from config files -> connect -> make


# Finish

```{r disconnect}
DBI::dbDisconnect(DB1$con)
```

<!-- ```{r, save DAG} -->
<!-- if (!dir.exists("./.rflow")) dir.create(path = "./.rflow") -->
<!-- save(list = ls(DAG, all.names = TRUE), envir = DAG, file = "./.rflow/DAG.RData") -->
<!-- ``` -->

